
services:
  db:
    image: mysql:8.0
    container_name: hotel-db
    restart: always
    environment:
      MYSQL_DATABASE: hotel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hotel-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: hotel-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hotel
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy # wait for MySQL to pass healthcheck
    ports:
      - "8083:8080"
    networks:
      - hotel-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: hotel-frontend
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - backend
    networks:
      - hotel-net

volumes:
  db_data:

networks:
  hotel-net:
    driver: bridge
